apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-bigip-ctlr-deployment-kic
  namespace: kube-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: k8s-bigip-ctlr-kic
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        seccomp.security.alpha.kubernetes.io/defaultProfileName: unconfined
        seccomp.security.alpha.kubernetes.io/pod: unconfined
      creationTimestamp: ~
      labels:
        app: k8s-bigip-ctlr-kic
      name: k8s-bigip-ctlr-kic
    spec:
      containers:
        -
          args:
            - "--bigip-username=$(BIGIP_USERNAME)"
            - "--bigip-password=$(BIGIP_PASSWORD)"
            - "--bigip-url=-bigip-mgmt-address-"
            - "--bigip-partition=kic"
            - "--namespace=nginx-ingress"
            #- "--pool-member-type=nodeport"
            - "--pool-member-type=cluster"
            # - "--flannel-name=fl-vxlan"
            - "--log-level=DEBUG"
            - "--insecure=true"
            - "--manage-ingress=true"
            - "--manage-routes=false"
            - "--manage-configmaps=true"
            - "--as3-validation=false"
            - "--agent=as3"
          command:
            - /app/bin/k8s-bigip-ctlr
          env:
            -
              name: BIGIP_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: bigip-login-kic
            -
              name: BIGIP_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: bigip-login-kic
          image: "f5networks/k8s-bigip-ctlr:2.2.3"
          name: f5-server
      serviceAccountName: k8s-bigip-ctlr-kic
